language: c
language: python

python:
    - "3.4"

install: "pip install requests"

addons:
    apt:
        packages:
            - python3    


script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd test
    - make
    - ./test.sh
