addons:
    apt:
        packages:
            - python3    
            - python3-pip

before_install:
    pip3 install requests

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd test
    - make
    - ./test.sh
